---
# tasks file for logstash
- name: Add Elasticsearch GPG key.
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Logstash repository.
  template:
    src: logstash.repo.j2
    dest: /etc/yum.repos.d/logstash.repo
    mode: 0644

- name: Install Logstash.
  package:
    name: logstash
    state: present

- name: Open firewall ports for logstash
  firewalld:
    port: 5044/tcp
    permanent: yes
    state: enabled
